package com.simple.adapter.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName

/**
 * KSP Symbol Processor chính cho thư viện Adapter.
 *
 * Processor này chạy tại **compile-time**, quét toàn bộ source code để tìm
 * các class có annotation [@Adapter][com.simple.adapter.Adapter], sau đó
 * tự động sinh ra file `{ModuleName}ViewItemAdapterProvider.kt` đăng ký
 * tất cả các adapter đó vào [ViewItemAdapterProvider][com.simple.adapter.ViewItemAdapterProvider].
 *
 * ## Luồng hoạt động tổng quan
 * ```
 * Gradle build
 *   → KSP plugin kích hoạt AdapterProcessorProvider
 *   → AdapterProcessor.process() được gọi
 *   → Tìm tất cả class có @Adapter
 *   → Validate từng class
 *   → Sinh ra {ModuleName}ViewItemAdapterProvider.kt
 * ```
 *
 * ## File được sinh ra có dạng
 * ```kotlin
 * // Generated by AdapterProcessor. DO NOT EDIT.
 * @AutoRegister(apis = [ViewItemAdapterProvider::class])
 * class ModuleNameViewItemAdapterProvider : ViewItemAdapterProvider() {
 *
 *     override fun provider(): List<String> = listOf(
 *         NoneAdapter::class.java.name,
 *         OtherAdapter::class.java.name,
 *     )
 * }
 * ```
 *
 * @param codeGenerator Công cụ KSP để tạo và ghi file Kotlin mới.
 * @param logger        Logger để báo lỗi/cảnh báo trong quá trình build.
 * @param options       Các option do KSP Gradle plugin tự inject — bao gồm `moduleName`
 *                      lấy từ tên Gradle module, không cần cấu hình thủ công.
 *
 * @see AdapterProcessorProvider
 * @see com.simple.adapter.Adapter
 */
class AdapterProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>,
) : SymbolProcessor {

    companion object {
        /** Fully-qualified name của annotation [@Adapter][com.simple.adapter.Adapter]. */
        const val ADAPTER_ANNOTATION = "com.simple.adapter.Adapter"

        /**
         * Fully-qualified name của abstract class
         * [ViewItemAdapterProvider][com.simple.adapter.ViewItemAdapterProvider].
         *
         * Class sinh ra sẽ extend class này và override hàm `provider()`.
         */
        const val VIEW_ITEM_ADAPTER_PROVIDER = "com.simple.adapter.ViewItemAdapterProvider"

        /**
         * Fully-qualified name của annotation
         * [@AutoRegister][com.simple.auto.register.AutoRegister].
         *
         * Annotation này báo cho AutoRegisterManager biết class cần được tự động
         * khởi tạo và đăng ký khi app start.
         */
        const val AUTO_REGISTER = "com.simple.auto.register.AutoRegister"

        private val LIST   = ClassName("kotlin.collections", "List")
        private val STRING = ClassName("kotlin", "String")
    }

    // ─── Entry Point ──────────────────────────────────────────────────────────

    /**
     * Điểm vào chính của KSP — được gọi **mỗi round** compile.
     *
     * KSP có thể gọi [process] nhiều lần (multi-round processing) vì một số
     * symbol có thể chưa resolve được ở round đầu. Các symbol chưa resolve
     * sẽ được trả về để retry.
     *
     * ## Thứ tự xử lý
     * 1. Lấy tất cả symbol có annotation `@Adapter`
     * 2. Lọc ra những symbol đã resolve đầy đủ và hợp lệ
     * 3. Nếu có symbol hợp lệ → sinh code
     * 4. Trả về các symbol chưa resolve để KSP retry ở round sau
     *
     * @param resolver Cho phép truy vấn các symbol trong source code hiện tại.
     * @return Danh sách symbol chưa resolve — sẽ được xử lý lại ở round sau.
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.warn("[AdapterProcessor] process() called")

        val symbols = resolver.getSymbolsWithAnnotation(ADAPTER_ANNOTATION)
        val symbolList = symbols.toList()
        logger.warn("[AdapterProcessor] found ${symbolList.size} symbol(s) with @Adapter")
        symbolList.forEach { logger.warn("[AdapterProcessor]   symbol: $it") }

        val validAdapters = collectValidAdapters(symbolList.asSequence())
        logger.warn("[AdapterProcessor] valid adapters: ${validAdapters.size}")

        if (validAdapters.isNotEmpty()) {
            generate(validAdapters)
        } else {
            logger.warn("[AdapterProcessor] no valid adapters found — skipping code generation")
        }

        val deferred = symbolList.filterNot { it.validate() }
        logger.warn("[AdapterProcessor] deferred (unresolved) symbols: ${deferred.size}")
        return deferred
    }

    // ─── Collect ──────────────────────────────────────────────────────────────

    /**
     * Lọc ra danh sách các adapter class hợp lệ từ tập symbol đầu vào.
     *
     * Một class được đưa vào danh sách kết quả khi thoả mãn **cả 3** điều kiện:
     * 1. Là [KSClassDeclaration] (không phải function, property, type alias, v.v.)
     * 2. Đã được KSP resolve đầy đủ ([KSAnnotated.validate] = `true`)
     * 3. Thoả mãn các ràng buộc business trong [validateAdapter]
     *
     * @param symbols Sequence các symbol có annotation `@Adapter`.
     * @return Danh sách class hợp lệ, sẵn sàng để sinh code.
     */
    private fun collectValidAdapters(symbols: Sequence<KSAnnotated>): List<KSClassDeclaration> {
        return symbols
            .filterIsInstance<KSClassDeclaration>()
            .also { seq ->
                val nonClass = symbols.filterNot { it is KSClassDeclaration }.toList()
                if (nonClass.isNotEmpty())
                    logger.warn("[AdapterProcessor] skipped ${nonClass.size} non-class symbol(s): $nonClass")
            }
            .filter {
                val ok = it.validate()
                if (!ok) logger.warn("[AdapterProcessor] not yet resolvable (will retry): ${it.qualifiedName?.asString()}")
                ok
            }
            .filter { validateAdapter(it) }
            .toList()
    }

    // ─── Validate ─────────────────────────────────────────────────────────────

    /**
     * Kiểm tra toàn diện xem một class có đủ điều kiện làm Adapter không.
     *
     * @param classDecl Class cần kiểm tra.
     * @return `true` nếu class hợp lệ, `false` nếu vi phạm bất kỳ điều kiện nào.
     */
    private fun validateAdapter(classDecl: KSClassDeclaration): Boolean {
        return checkNotAbstractOrSealed(classDecl)
    }

    /**
     * Kiểm tra class không phải abstract hoặc sealed.
     *
     * **Lý do:** Abstract/sealed class không thể lấy `.java.name` để tạo instance
     * tại runtime — code sinh ra sẽ không hoạt động đúng.
     *
     * @param classDecl Class cần kiểm tra.
     * @return `true` nếu class là concrete class (có thể khởi tạo được).
     */
    private fun checkNotAbstractOrSealed(classDecl: KSClassDeclaration): Boolean {
        val isAbstractOrSealed = Modifier.ABSTRACT in classDecl.modifiers
                || Modifier.SEALED in classDecl.modifiers

        if (isAbstractOrSealed) {
            logger.error(
                "@Adapter không thể dùng trên abstract/sealed class: ${classDecl.simpleName.asString()}",
                classDecl
            )
        } else {
            logger.warn("[AdapterProcessor] validated OK: ${classDecl.qualifiedName?.asString()}")
        }

        return !isAbstractOrSealed
    }

    // ─── Generate ─────────────────────────────────────────────────────────────

    /**
     * Điều phối toàn bộ quá trình sinh code từ danh sách adapter đã validate.
     *
     * - **Package** lấy từ package của adapter đầu tiên — giống [DeeplinkProcessor].
     * - **ModuleName** lấy theo thứ tự ưu tiên (giống [AutoRegisterProcessor.resolveModuleInfo]):
     *   1. `options["moduleName"]` nếu được truyền thủ công qua KSP config.
     *   2. [extractModuleName] từ đường dẫn file source của adapter đầu tiên —
     *      tìm segment ngay trước `src/` trong path, đó chính là tên thư mục module.
     *
     * Ví dụ: `.../feature-payment/src/main/...` → moduleName = `feature-payment`
     * → className = `FeaturePaymentViewItemAdapterProvider`
     *
     * @param classDecls Danh sách adapter đã được validate.
     */
    private fun generate(classDecls: List<KSClassDeclaration>) {
        val packageName = classDecls.first().packageName.asString()

        val firstFilePath = classDecls.first().containingFile?.filePath.orEmpty()
        val moduleName = options["moduleName"] ?: extractModuleName(firstFilePath)

        val pascal = moduleName
            .split("-", "_")
            .joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
        val className = "${pascal}ViewItemAdapterProvider"

        logger.warn("[AdapterProcessor] generating → package=$packageName, class=$className")
        logger.warn("[AdapterProcessor] firstFilePath=$firstFilePath")
        logger.warn("[AdapterProcessor] moduleName=$moduleName (from ${if (options.containsKey("moduleName")) "ksp option" else "file path"})")
        logger.warn("[AdapterProcessor] adapters: ${classDecls.map { it.simpleName.asString() }}")

        val fileSpec = buildFileSpec(packageName, className, classDecls)
        writeToFile(fileSpec, packageName, className, classDecls)
    }

    /**
     * Trích xuất tên module từ đường dẫn file source.
     *
     * Chiến lược (giống [AutoRegisterProcessor]):
     * 1. Tìm thư mục ngay trước `src/` → đây là tên module chuẩn.
     * 2. Tìm thư mục ngay trước `build/` → dùng cho file do KSP khác generate.
     * 3. Fallback về "GeneratedModule" nếu không xác định được.
     *
     * Ví dụ: `.../feature-payment/src/main/kotlin/…` → "feature-payment"
     *
     * @param path Đường dẫn tuyệt đối của file source chứa class được annotate.
     * @return Tên thư mục module.
     */
    private fun extractModuleName(path: String): String {
        val parts = path.replace("\\", "/").split("/")

        val srcIndex = parts.indexOf("src")
        if (srcIndex > 0) return parts[srcIndex - 1]

        val buildIndex = parts.indexOf("build")
        if (buildIndex > 0) return parts[buildIndex - 1]

        return "GeneratedModule"
    }

    /**
     * Xây dựng [FileSpec] — đại diện cho toàn bộ nội dung file `.kt` sẽ được sinh.
     *
     * @param packageName Package của file được sinh ra.
     * @param className   Tên class được sinh ra.
     * @param classDecls  Danh sách adapter để đưa vào body class.
     * @return [FileSpec] sẵn sàng để ghi ra disk.
     */
    private fun buildFileSpec(
        packageName: String,
        className: String,
        classDecls: List<KSClassDeclaration>,
    ): FileSpec {
        return FileSpec.builder(packageName, className)
            .addFileComment("Generated by AdapterProcessor. DO NOT EDIT.")
            .addType(buildClassSpec(className, classDecls))
            .build()
    }

    /**
     * Xây dựng [TypeSpec] cho class `{ModuleName}ViewItemAdapterProvider`.
     *
     * Class được sinh ra có cấu trúc:
     * ```kotlin
     * @AutoRegister(apis = [ViewItemAdapterProvider::class])
     * class ModuleNameViewItemAdapterProvider : ViewItemAdapterProvider() {
     *     override fun provider(): List<String> = listOf(...)
     * }
     * ```
     *
     * Annotation `@AutoRegister` giúp [AutoRegisterManager][com.simple.auto.register.AutoRegisterManager]
     * tự động tìm thấy và gọi `provider()` mà không cần khai báo thủ công.
     *
     * @param className  Tên class được sinh ra.
     * @param classDecls Danh sách adapter để đưa vào hàm `provider()`.
     * @return [TypeSpec] của class provider.
     */
    private fun buildClassSpec(className: String, classDecls: List<KSClassDeclaration>): TypeSpec {
        val providerClass = ClassName.bestGuess(VIEW_ITEM_ADAPTER_PROVIDER)
        val autoRegister  = ClassName.bestGuess(AUTO_REGISTER)

        return TypeSpec.classBuilder(className)
            .addAnnotation(buildAutoRegisterAnnotation(autoRegister, providerClass))
            .superclass(providerClass)
            .addFunction(buildProviderFunction(classDecls))
            .build()
    }

    /**
     * Xây dựng [AnnotationSpec] cho `@AutoRegister(apis = [ViewItemAdapterProvider::class])`.
     *
     * @param autoRegister  ClassName của `@AutoRegister`.
     * @param providerClass ClassName của [ViewItemAdapterProvider][com.simple.adapter.ViewItemAdapterProvider].
     * @return [AnnotationSpec] đã build xong.
     */
    private fun buildAutoRegisterAnnotation(
        autoRegister: ClassName,
        providerClass: ClassName,
    ): AnnotationSpec {
        return AnnotationSpec.builder(autoRegister)
            .addMember(CodeBlock.of("apis = [%T::class]", providerClass))
            .build()
    }

    /**
     * Xây dựng hàm `provider()` — override từ [ViewItemAdapterProvider][com.simple.adapter.ViewItemAdapterProvider].
     *
     * Với mỗi adapter trong [classDecls], hàm sẽ thêm một entry:
     * ```kotlin
     * NoneAdapter::class.java.name,
     * ```
     *
     * Kết quả sinh ra:
     * ```kotlin
     * override fun provider(): List<String> = listOf(
     *     NoneAdapter::class.java.name,
     *     OtherAdapter::class.java.name,
     * )
     * ```
     *
     * @param classDecls Danh sách adapter cần đăng ký.
     * @return [FunSpec] của hàm `provider()`.
     */
    private fun buildProviderFunction(classDecls: List<KSClassDeclaration>): FunSpec {
        val returnType = LIST.parameterizedBy(STRING)

        val listBody = CodeBlock.builder()
            .add("return listOf(\n")
            .indent()
            .apply {
                classDecls.forEach { classDecl ->
                    add("%T::class.java.name,\n", classDecl.toClassName())
                }
            }
            .unindent()
            .add(")")
            .build()

        return FunSpec.builder("provider")
            .addModifiers(KModifier.OVERRIDE)
            .returns(returnType)
            .addCode(listBody)
            .build()
    }

    // ─── Write ────────────────────────────────────────────────────────────────

    /**
     * Ghi [FileSpec] ra file `.kt` thực tế trên disk thông qua [codeGenerator].
     *
     * ## Về Dependencies với `aggregating = true`
     * Khi `aggregating = true`, KSP biết rằng file sinh ra này phụ thuộc vào
     * **tất cả** source file chứa adapter. Nếu **bất kỳ** file nào thêm/xoá/sửa
     * một `@Adapter` class, toàn bộ file sinh ra sẽ được tái sinh.
     *
     * @param fileSpec    FileSpec đã build, chứa nội dung cần ghi.
     * @param packageName Package của file sinh ra.
     * @param className   Tên file (và class) sinh ra.
     * @param classDecls  Danh sách adapter — dùng để tính [Dependencies].
     */
    private fun writeToFile(
        fileSpec: FileSpec,
        packageName: String,
        className: String,
        classDecls: List<KSClassDeclaration>,
    ) {
        val dependencies = Dependencies(
            aggregating = true,
            *classDecls.mapNotNull { it.containingFile }.toTypedArray()
        )

        try {
            codeGenerator.createNewFile(
                dependencies = dependencies,
                packageName = packageName,
                fileName = className,
            ).bufferedWriter().use { writer ->
                fileSpec.writeTo(writer)
            }
            logger.warn("[AdapterProcessor] file written: $packageName.$className")
        } catch (e: Exception) {
            logger.error("[AdapterProcessor] FAILED to write file $packageName.$className: ${e.message}")
        }
    }
}
